# Makefile.dep created Thu Jul 26 14:20:16 PDT 2018
logstream.o: logstream.h
protocol.o: protocol.h sockets.h
protocol.o: protocol.cpp protocol.h sockets.h
sockets.o: sockets.h
sockets.o: sockets.cpp sockets.h
cix.o: cix.cpp protocol.h sockets.h logstream.h
cixd.o: cixd.cpp protocol.h sockets.h logstream.h
